import { Providers } from "../providers";
import "reveal.js/dist/reveal.css";
import "reveal.js/dist/theme/black.css";
import "../styles/theme.css";
import "../styles/global.css";
import type { Metadata } from "next";
import type { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: ["favicon.ico"],
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="h-full">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
